### ISSUE TITLE
Add build for golang v1.9.3 version

### ISSUE THREAD

**Issue by celskeggs** [sipb/homeworld#100]
Upstream: [v1.9.3](https://golang.org/dl/)

Upstream update checklist:
- [x] Ensure upstream version is latest.
- [x] Review changelogs for breaking changes.
- [x] Securely verify upstream release hash.
- [x] Add add-go-1.9.3 branch with update.
- [x] Implement any repackaging changes.
- [x] Test cluster deployment with changes.
- [ ] File related issues (e.g. those from the changelog scanning.)
- [ ] Merge changes.

This isn't a ticket to update the version of Go, but to have a side-by-side newer version of Go, which we can migrate individual components over to. Kubernetes, for example, will continue needing Go 1.8 for the time being.

**Comment by celskeggs** [comment]
[Changelog](https://golang.org/doc/go1.9)

Possible breaking changes:

 * On Linux, Go now calls the getrandom system call without the GRND_NONBLOCK flag; it will now block until the kernel has sufficient randomness. On kernels predating the getrandom system call, Go continues to read from /dev/urandom. (This is probably a good thing, of course.)
 * If any SAN extension, including with no DNS names, is present in the certificate, then the Common Name from Subject is ignored. In previous releases, the code tested only whether DNS-name SANs were present in a certificate.

There is at least one useful feature as well:

 * If any SAN extension, including with no DNS names, is present in the certificate, then the Common Name from Subject is ignored. In previous releases, the code tested only whether DNS-name SANs were present in a certificate.

**Comment by ichung** [comment]
Is the SAN extension behavior "breaking" or "useful"?On Oct 7, 2017 11:58, Cel Skeggs <notifications@github.com> wrote:Changelog
Possible breaking changes:
On Linux, Go now calls the getrandom system call without the GRND_NONBLOCK flag; it will now block until the kernel has sufficient randomness. On kernels predating the getrandom system call, Go continues to read from /dev/urandom. (This is probably a good thing, of course.)If any SAN extension, including with no DNS names, is present in the certificate, then the Common Name from Subject is ignored. In previous releases, the code tested only whether DNS-name SANs were present in a certificate.
There is at least one useful feature as well:
If any SAN extension, including with no DNS names, is present in the certificate, then the Common Name from Subject is ignored. In previous releases, the code tested only whether DNS-name SANs were present in a certificate.

**Comment by celskeggs** [comment]
Woops. I copy-pasted wrong. I meant to include the test helper extension.

**Comment by celskeggs** [comment]
Woops, wrong issue.

**Comment by ichung** [comment]
It looks like the subject name change only applies to hostname validation.  Since we don't use the Subject field for hostnames, this shouldn't be a problem.
