### ISSUE TITLE
Audit Lintian warnings for Debian packages

### ISSUE THREAD

**Issue by andersk** [sipb/homeworld#116]
If you configure `sbuild` to run `lintian` in `~/.sbuildrc`:

```
$run_lintian = 1;
1;
```

then you get a bunch of messages about the built Debian packages, some of which we should pay attention to ([documentation](https://lintian.debian.org/)).

> W: homeworld-admin-tools source: debhelper-but-no-misc-depends homeworld-admin-tools
> W: homeworld-apt-setup source: debhelper-but-no-misc-depends homeworld-apt-setup
> W: homeworld-bootstrap-registry source: debhelper-but-no-misc-depends homeworld-bootstrap-registry
> W: homeworld-etcd source: debhelper-but-no-misc-depends homeworld-etcd
> W: homeworld-hyperkube source: debhelper-but-no-misc-depends homeworld-hyperkube
> W: homeworld-hyperkube: missing-depends-line
> W: homeworld-keysystem source: debhelper-but-no-misc-depends homeworld-keysystem
> E: homeworld-keysystem: missing-dependency-on-libc needed by usr/bin/keyclient and 5 others
> W: homeworld-knc source: debhelper-but-no-misc-depends homeworld-knc
> E: homeworld-knc: missing-dependency-on-libc needed by usr/bin/knc
> W: homeworld-rkt source: package-depends-on-hardcoded-libc homeworld-rkt depends
> W: homeworld-rkt source: debhelper-but-no-misc-depends homeworld-rkt
> W: homeworld-services source: debhelper-but-no-misc-depends homeworld-services

- [x] All packages need `${misc:Depends}`.
- [x] Packages with binaries or libraries need `${shlibs:Depends}`.

> W: homeworld-admin-tools source: ancient-standards-version 3.9.6 (current is 3.9.8)
> W: homeworld-apt-setup source: ancient-standards-version 3.9.6 (current is 3.9.8)
> W: homeworld-bootstrap-registry source: ancient-standards-version 3.9.6 (current is 3.9.8)
> W: homeworld-etcd source: ancient-standards-version 3.9.6 (current is 3.9.8)
> W: homeworld-hyperkube source: ancient-standards-version 3.9.6 (current is 3.9.8)
> W: homeworld-keysystem source: ancient-standards-version 3.9.6 (current is 3.9.8)
> W: homeworld-knc source: ancient-standards-version 3.9.6 (current is 3.9.8)
> W: homeworld-rkt source: ancient-standards-version 3.9.6 (current is 3.9.8)
> W: homeworld-services source: ancient-standards-version 3.9.6 (current is 3.9.8)

- [x] Little consequence for us, but easy to bump.

> W: homeworld-admin-tools: syntax-error-in-debian-changelog line 11 "couldn't parse date Thr, 05 Oct 2017 01:21:00 -0400"
> W: homeworld-bootstrap-registry: syntax-error-in-debian-changelog line 29 "couldn't parse date Thr, 20 Jul 2017 22:42:28 -0400"
> W: homeworld-bootstrap-registry: debian-changelog-has-wrong-day-of-week 2017-09-09 is a Saturday
> W: homeworld-bootstrap-registry: latest-debian-changelog-entry-without-new-date
> W: homeworld-services: syntax-error-in-debian-changelog line 83 "couldn't parse date Thr, 13 Jul 2017 22:35:55 -0400"

- [x] Thursday is Thu, not Thr, and October is 10, not 09.  Are you writing these `debian/changelog` entries manually?  Use [`dch`](https://manpages.debian.org/stretch/devscripts/debchange.1.en.html) or Emacs’ [`debian-changelog-mode`](https://www.emacswiki.org/emacs/EmacsForDebian) instead.  This will become important for reproducibility since `SOURCE_DATE_EPOCH` is computed from `debian/changelog`.

> E: homeworld-admin-tools: copyright-contains-dh_make-todo-boilerplate
> E: homeworld-etcd: copyright-contains-dh_make-todo-boilerplate
> E: homeworld-hyperkube: copyright-contains-dh_make-todo-boilerplate
> E: homeworld-keysystem: copyright-contains-dh_make-todo-boilerplate
> W: homeworld-knc source: file-without-copyright-information .gitignore
> W: homeworld-knc source: file-without-copyright-information build-package.sh
> W: homeworld-knc source: file-without-copyright-information inner-build.sh
> W: homeworld-knc source: file-without-copyright-information knc-1.7.1.tar.xz
> E: homeworld-knc: copyright-contains-dh_make-todo-boilerplate

- [ ] Annoying, but we should keep accurate copyright information.

> W: homeworld-admin-tools: binary-without-manpage usr/bin/spire
> W: homeworld-etcd: binary-without-manpage usr/bin/etcdctl
> W: homeworld-hyperkube: binary-without-manpage usr/bin/hyperkube
> W: homeworld-keysystem: binary-without-manpage usr/bin/keyclient
> W: homeworld-keysystem: binary-without-manpage usr/bin/keygateway
> W: homeworld-keysystem: binary-without-manpage usr/bin/keygen
> W: homeworld-keysystem: binary-without-manpage usr/bin/keyinitadmit
> W: homeworld-keysystem: binary-without-manpage usr/bin/keyreq
> W: homeworld-keysystem: binary-without-manpage usr/bin/keyserver
> W: homeworld-knc: binary-without-manpage usr/bin/knc
> W: homeworld-rkt: binary-without-manpage usr/bin/rkt

Ignorable, I suppose, since we’re not uploading to Debian.

> E: homeworld-apt-setup: package-installs-apt-preferences etc/apt/preferences.d/
> E: homeworld-apt-setup: package-installs-apt-preferences etc/apt/preferences.d/homeworld.pref
> E: homeworld-apt-setup: package-installs-apt-sources etc/apt/sources.list.d/
> E: homeworld-apt-setup: package-installs-apt-sources etc/apt/sources.list.d/homeworld.sources

By design.

> W: homeworld-etcd source: native-package-with-dash-version
> W: homeworld-hyperkube source: native-package-with-dash-version
> W: homeworld-knc source: native-package-with-dash-version
> W: homeworld-rkt source: native-package-with-dash-version

- [ ] Our source packages are weird compared to Debian’s.  We could disable generation of source packages, or we could fix them to make more sense.

> E: homeworld-etcd: statically-linked-binary usr/bin/etcdctl

Probably by design?

> W: homeworld-keysystem: hardening-no-relro usr/bin/keyclient
> W: homeworld-keysystem: hardening-no-relro usr/bin/keygateway
> W: homeworld-keysystem: hardening-no-relro usr/bin/keygen
> W: homeworld-keysystem: hardening-no-relro usr/bin/keyinitadmit
> W: homeworld-keysystem: hardening-no-relro usr/bin/keyreq
> W: homeworld-keysystem: hardening-no-relro usr/bin/keyserver

- [ ] This might be security relevant?

> E: homeworld-keysystem: systemd-service-file-outside-lib usr/lib/systemd/system/keyclient.service
> E: homeworld-keysystem: systemd-service-file-outside-lib usr/lib/systemd/system/keygateway.service
> E: homeworld-keysystem: systemd-service-file-outside-lib usr/lib/systemd/system/keyserver.service
> E: homeworld-keysystem: systemd-service-file-outside-lib usr/lib/systemd/system/update-keyclient-config.service
> E: homeworld-rkt: systemd-service-file-outside-lib usr/lib/systemd/system/rkt-api.service
> E: homeworld-rkt: systemd-service-file-outside-lib usr/lib/systemd/system/rkt-gc.service
> E: homeworld-rkt: systemd-service-file-outside-lib usr/lib/systemd/system/rkt-metadata.service
> E: homeworld-services: systemd-service-file-outside-lib usr/lib/systemd/system/apiserver.service
> E: homeworld-services: systemd-service-file-outside-lib usr/lib/systemd/system/etcd.service
> E: homeworld-services: systemd-service-file-outside-lib usr/lib/systemd/system/kube-ctrlmgr.service
> E: homeworld-services: systemd-service-file-outside-lib usr/lib/systemd/system/kube-proxy.service
> E: homeworld-services: systemd-service-file-outside-lib usr/lib/systemd/system/kube-scheduler.service
> E: homeworld-services: systemd-service-file-outside-lib usr/lib/systemd/system/kubelet.service
> W: homeworld-services: maintainer-script-calls-systemctl prerm:22

- [ ] systemd service files on Debian go in `/lib`, not `/usr/lib`, but more generally, they should be packaged [with `dh_systemd`](https://wiki.debian.org/Teams/pkg-systemd/Packaging), which automatically generates appropriate maintainer scripts.

> W: homeworld-knc: new-package-should-close-itp-bug

Ignorable since we’re not uploading to Debian.

> W: homeworld-rkt: command-with-path-in-maintainer-script preinst:12 /usr/bin/rkt
> W: homeworld-rkt: command-with-path-in-maintainer-script preinst:16 /usr/bin/rkt
> W: homeworld-rkt: command-with-path-in-maintainer-script prerm:9 /usr/bin/rkt
> W: homeworld-rkt: command-with-path-in-maintainer-script prerm:13 /usr/bin/rkt

- [x] It wants `rkt`, not `/usr/bin/rkt`.

**Comment by celskeggs** [comment]
The critical ones here seem like the changelog and hardening. I've split those off into #117 and #118. Everything else sounds like it can wait until someone feels like fixing them.

**Comment by celskeggs** [comment]
We don't use the normal debian packaging tools anymore, so there are no longer lintian warnings to check. Closing.
