### ISSUE TITLE
Change apiserver to use ABAC or RBAC instead of AlwaysAllow

### ISSUE THREAD

**Issue by celskeggs** [sipb/homeworld#12]
Kubernetes has two key phases of processing a request that are security-relevant:
 - Authentication: determining with confidence who or what is making this request.
 - Authorization: determining whether the entity making this request is allowed to make this particular request, or whether it's outside the scope of what they should be allowed to do.

For authentication, we're using a combination of kubernetes certificate authentication and serviceaccount-based authentication. This is likely to be something of a long-term solution.

For authorization, we're currently using AlwaysAllow -- which means that anyone authenticated to the cluster is allowed to perform any operation. This is insecure and a terrible idea.

This project is to review the available modes for kubernetes authorization (abac, rbac, webhooks), compare and contrast what they support, decide (with input from the homeworld primary maintainer) which one should be used, and then implement sample policy and/or policy generation for the chosen mode for use in the cluster. This also means testing the policy against the actual operations that will be performed and confirming that it doesn't break the cluster or allow privilege escalation that would compromise the cluster's security.

**Comment by celskeggs** [comment]
@coventry: How's this going? Am I correct in assuming that I should defer this to DC6, since it probably won't happen by this weekend?

**Comment by coventry** [comment]
Sorry I missed this. Yes.

**Comment by celskeggs** [comment]
Per discussion in the dev channel, we plan to use RBAC, at least until/unless we find a reason to switch to webhooks.

For now, since we won't have groups yet, the plan is to give each user access to the `user-<kerberos>` namespace via a RoleBinding added by user-grant to a global ClusterRole.
