### ISSUE TITLE
Bootstrap tokens should include a check code

### ISSUE THREAD

**Issue by ichung** [sipb/homeworld#132]
If you typo the code, you currently don't find out until it doesn't work later.  We should add a check code to prevent typos.

**Comment by celskeggs** [comment]
@guillde: do you expect to be able to resolve this issue in the near future? If not, we should unassign you so that it's freed up.

(We can also find you an easier issue, like #162 or #163.)

**Comment by guillde** [comment]
You can unassign the issue. And do not worry about finding me another issue.


________________________________

**Comment by celskeggs** [comment]
Solved by #216.
