### ISSUE TITLE
spire verify flannel-ping fails

### ISSUE THREAD

**Issue by ichung** [sipb/homeworld#134]
If one of the nodes doesn't have the homeworld.mit.edu/debian ACI, it takes too long to respond.  It is also otherwise flaky for an unknown reason.

**Comment by celskeggs** [comment]
This might be resolved by the latest changes to master. We should try to reproduce.

**Comment by celskeggs** [comment]
I think this has been resolved. If we experience flakiness with the flannel-ping test in the future, we should re-open this.
