### ISSUE TITLE
Streamline process of installing administration packages on a new system

### ISSUE THREAD

**Issue by celskeggs** [sipb/homeworld#142]
Currently, you have to somehow build or obtain a copy of homeworld-apt-setup.deb, and then install it directly. There should be an easier way.

**Comment by krawthekrow** [comment]
Could we distribute the deb publicly on Github? It could be signed, if security is an issue. Any easier and we'd be creating a ppa.

**Comment by celskeggs** [comment]
Yeah, we definitely could. That would be a reasonable way to bootstrap -- we might also consider sticking the file in AFS (so that we can provide a public link), signed of course.

**Comment by celskeggs** [comment]
Links: http://web.mit.edu/hyades/homeworld-apt-setup.deb and http://web.mit.edu/hyades/homeworld-apt-setup.deb.asc. Commit: 550bb58.
