### ISSUE TITLE
Confirm that a .pem is public material before sticking it into authorities.tgz

### ISSUE THREAD

**Issue by celskeggs** [sipb/homeworld#144]
Just in case.

Original comment: https://github.com/sipb/homeworld/pull/135#discussion_r154534577

In other words: instead of assuming that every `.pem` file is safe to copy as public information, we should read the headers on them to ensure that they contain a PEM certificate and not anything else.

**Comment by dmssargent** [comment]
Just to confirm, you only want .pem files to have just certificate(s) in them and nothing else per what is allowable by the format? Or do you want to ensure the .pem file does not contain any private keys?

For future reference, [RFC 7468](https://tools.ietf.org/html/rfc7468) specifies the encapsulation methods used in the PEM file format, while [RFC 1421](https://tools.ietf.org/html/rfc1421) Section 4.4 considers only the text that is encapsulated to be a PEM message. OpenSSL's [pem.h](https://github.com/openssl/openssl/blob/master/include/openssl/pem.h) can show us what types of messages PEM files can carry.

**Comment by ichung** [comment]
@dmssargent The former - there should be only a certificate and nothing else.

**Comment by dmssargent** [comment]
Thanks @ichung!

**Comment by dmssargent** [comment]
If a file is found that has the extension of ".pem" but contains >1 certificates or contains other things (like a private key), what should my code do?

**Comment by celskeggs** [comment]
Throw an exception. Probably just use command.fail for that.
