### ISSUE TITLE
Improve build instructions

### ISSUE THREAD

**Issue by andersk** [sipb/homeworld#166]
docs/build.md:

* Should mention pull-upstream.sh.
* Should list debhelper as a prerequisite (used to build source packages).
* Should list sudo as a prerequisite (used by build-acis).
* Should list python3 as a prerequisite (used by build-acis in a oneliner to list nameservers, though that should maybe just use awk or something).
* Should list systemd-container as a prerequisite (acbuild uses systemd-nspawn by default).
* Should maybe list debootstrap as a prerequisite (used by build-acis, though sbuild recommends it).
* Should not list cpio, genisoimage as prerequisites (they’re pulled in as needed inside the sbuild chroot, but not used outside).
* `homeworld-rkt-<newest>.deb` should be `homeworld-rkt_<newest>.deb`.
* After `dpkg -i homeworld-rkt_<newest>.deb`, run `apt install -f` to resolve any dependency problems.
* `//building` is a confusing metasyntax (or typo?), maybe use relative paths instead?

**Comment by andersk** [comment]
> * Should not list cpio, genisoimage as prerequisites (they’re pulled in as needed inside the sbuild chroot, but not used outside).

Although the homeworld-admin-tools package might be missing Depends: cpio.

**Comment by celskeggs** [comment]
> Should not list cpio, genisoimage as prerequisites (they’re pulled in as needed inside the sbuild chroot, but not used outside).

People run `inner-build.sh` directly during development, so it's useful to have them installed outside of the schroot.

Agree with the rest, though.
