### ISSUE TITLE
spire seq command should be more transparent

### ISSUE THREAD

**Issue by celskeggs** [sipb/homeworld#173]
Since each of these is essentially a sequence of simpler commands, people using them should be told the equivalent commands, for the sake of better understanding what's going on under the hood.

**Comment by krawthekrow** [comment]
Some solutions:

- Transcribe them somewhere in the wiki. Easy, but can get outdated.
- Modify Operations in a way that allows Spire to mock-up a command and display a set of manual instructions. This would require some structural changes.
- Turn the seq commands into bash scripts or something similar.
- Do nothing. After all, people can just look at Spire's code if they want to know _exactly_ what it's doing.

I like a combination of the first and fourth -- that was what the Homeworld's Build/Deployment Process pages on the wiki were supposed to be for. Also, it applies to commands beyond the seq group.

**Comment by ichung** [comment]
I prefer your second solution

**Comment by celskeggs** [comment]
The problem with the second solution is that you don't necessarily want to go into complete detail -- you just want the few top-level commands that do something similar.

bash scripts would be a fine idea, except that they're the exact thing that spire is supposed to avoid, because you end up with far too many complicated and brittle scripts...

The simplest solution might just be to have each `seq` command just `print()` out the list of commands that it's equivalent to.

**Comment by ichung** [comment]
> The simplest solution might just be to have each seq command just print() out the list of commands that it's equivalent to.

This is what I envisioned by the second solution

**Comment by celskeggs** [comment]
Ahh -- I was trying to avoid the part of the second solution that involved structural changes.

**Comment by ichung** [comment]
I think I miscommunicated my intent - automating this would still be important.

**Comment by krawthekrow** [comment]
How about having the seq commands feed string commands through the command parser, instead of calling the functions directly? Then we'd be able to attach a hook to print them out in a formatted manner. It'd be like bash scripts, but contained within Spire.

**Comment by ichung** [comment]
That sounds like a step backwards.  I would suggest to reify the operations themselves into objects which know what the associated command should be.

**Comment by celskeggs** [comment]
However, individual operations do not map 1-1 to commands, so that gets more complicated.

An easier solution: we could just have the Operations object keep a list of the commands it represents, and have a method that adds annotations -- i.e. the list of equivalent commands.

**Comment by ichung** [comment]
> individual operations do not map 1-1 to commands

Why not?  I think we should aim for operations to map 1-1 to commands.  In my vision the `seq` commands should just be abbreviations for sequences of other spire commands.

**Comment by celskeggs** [comment]
Because an "operation" is a defined concept in Spire, and correspond to the smallest unit of functionality in the sequencing system. The point of transparency is not to list every individual micro-level action that will be taken, but to list the small number of high-level non-`seq` spire commands to which each `seq` command is equivalent.

`seq` commands are already abbreviations for sequences of other spire commands.

**Comment by ichung** [comment]
> `seq` commands are already abbreviations for sequences of other spire commands

Can we reify whatever sort of object "other spire commands" refers to in this sentence?  Is a "spire command" equivalent to something I can run from the command-line?

**Comment by celskeggs** [comment]
Other spire commands, as in things that can be invoked from the command line.

For example, `spire seq keysystem` is equivalent to this set of commands:

    $ spire setup keyserver
    $ spire verify keystatics
    $ spire setup self-admit
    $ spire setup keygateway
    $ spire verify keygateway

**Comment by ichung** [comment]
My point is that we shouldn't have to manually print out the equivalent commands since spire should be smart enough to know what they are if we organize the `seq` infrastructure correclty.

**Comment by ichung** [comment]
I think I like mark's suggestion

> How about having the seq commands feed string commands through the command parser, instead of calling the functions directly? Then we'd be able to attach a hook to print them out in a formatted manner. It'd be like bash scripts, but contained within Spire.

more now.

**Comment by celskeggs** [comment]
re: your point: I am aware. The idea behind the solution I suggested earlier is that the `seq` commands don't need to annotate the commands they're running, but the other commands they dispatch to will add those annotations, and so the collection of annotations is built in the same way that the collection of operations is built.

re: mark's suggestion: I'm not yet convinced I like dispatching through the command parser; I'll think about that.

**Comment by ichung** [comment]
I'm not sure entirely about whether dispatching through the command parser is the exact right structure, but I would like a single point of truth for the mapping between command-line invocations and the actual commands.  I think a problem with "annotations" is that (regardless of where they're added) the annotations still need to be kept up to date with the parser.

**Comment by celskeggs** [comment]
I think it's possible to automatically figure out annotations without making our own scripting language. Give me a bit to give it a try.

**Comment by celskeggs** [comment]
I have a proposed solution back on #178. Let's move back there.
