### ISSUE TITLE
Consider splitting the keysystem out into a separate project

### ISSUE THREAD

**Issue by celskeggs** [sipb/homeworld#174]
Since almost everything here is just glue, it seems weird to have one component (keysystem) that is housed in-tree.

Thoughts on whether we should make it a separate project, and just package and deploy it here?

**Comment by ichung** [comment]
I think we should leave it in-tree, because:

1. The keysystem probably isn't useful to any project other than hyades.
2. Changes to homeworld and the keysystem will necessitate changes in each other

**Comment by celskeggs** [comment]
That makes sense.
