### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by ed1d1a8d** [sipb/homeworld#175]
Do we want to lint our code? Do we want to integrate linting into our build process? I was thinking of pylint and https://github.com/koalaman/shellcheck specifically.

**Comment by celskeggs** [comment]
Yes, it would be good for us to lint our code.

I'm not convinced that the build process is the right place; perhaps we should set up a validation check on PRs to ensure that they're linted?

**Comment by ed1d1a8d** [comment]
Yeah, I think linting when doing PRs is a better place. On a related note, should we also set up CI to build the PRs?

**Comment by celskeggs** [comment]
See: #24

**Comment by celskeggs** [comment]
Not on the critical path. Deferred to DC8.

**Comment by cryslith** [comment]
We should definitely run shellcheck in CI

**Comment by cryslith** [comment]
I also think we should run `pyflakes3` at a minimum on our python code.  The most useful thing it does is detect unused imports
