### ISSUE TITLE
Non-descriptive error code from keyreq

### ISSUE THREAD

**Issue by krawthekrow** [sipb/homeworld#179]
Keyreq's error code does not allow us to differentiate between the connection being down, invalid client tickets, or a broken server keygateway.

**Comment by celskeggs** [comment]
@krawthekrow: I don't remember the context for this; would you consider it sufficient to simply have keyreq print out more information on stderr?

**Comment by krawthekrow** [comment]
Keyreq, on error, always exits with error code 1, often with a non-descriptive error message. The error messages are currently distinct enough to diagnose from Spire by text matching, but that's a rather ugly solution. It would be convenient (and more in line with other utilities, like SSH) if keyreq returns different exit codes for different classes of errors (and also have more descriptive error messages, if it is intended to be used outside Spire).

**Comment by celskeggs** [comment]
It doesn't look possible to me to distinguish some of the above cases by the current output -- i.e. "server is down" versus "don't have tickets". But I can some of those along with adding more error codes.

**Comment by elefthei** [comment]
Looks like similar to this one I've been working on: https://github.com/sipb/homeworld/issues/176
@krawthekrow Agree keyreq needs better error messages

**Comment by celskeggs** [comment]
@krawthekrow: would you like to take this one? I worked on it previously (see the descriptive-error-codes branch), but never finished.

**Comment by celskeggs** [comment]
Fixed by #261.
