### ISSUE TITLE
Perform DNS bootstrap setup during ISO installation

### ISSUE THREAD

**Issue by celskeggs** [sipb/homeworld#188]
If node should start with DNS bootstrapping turned on, then it shouldn't require a command to run.

Part of #172.

**Comment by celskeggs** [comment]
@minced: how's this going?

**Comment by celskeggs** [comment]
@minced: do you expect to have time to finish this in the near future? If not, we'll need to assign someone else.

**Comment by celskeggs** [comment]
@minced: I remember that you showed me most of the required code for this in person recently, but I haven't heard much; if you won't be able to finish this by the meeting on Monday, can you at least post the code you have somewhere so that someone else can finish it?

**Comment by minced** [comment]
Hi! I'm so sorry I'm late. Code has been posted to the dns-bootstrap-during-iso-install branch. I will attempt to test my changes tonight if it's not too late.

**Comment by minced** [comment]
(Also note: I pushed to origin/dns-bootstrap... instead of minced/dns-bootstrap... at first; origin branch should probably be deleted)

**Comment by celskeggs** [comment]
Merged as part of #269.
