### ISSUE TITLE
rkt gc needs to be invoked periodically

### ISSUE THREAD

**Issue by celskeggs** [sipb/homeworld#211]
Otherwise, we start collecting thousands of ungc'd containers, especially now that we have aci-pull-monitor, which are incredibly slow to clean up, and cause fun problems like filling up the entire disk.

It doesn't look like rkt gc is running automatically. We should make sure it gets frequently invoked.

**Comment by andersk** [comment]
That’s supposed to be [this service’s job](https://github.com/rkt/rkt/blob/master/dist/init/systemd/rkt-gc.service), so this is a question of correctly packaging the systemd service with dh_systemd, which will cause it to be started automatically.

**Comment by celskeggs** [comment]
Or we can just enable it like we enable rkt-api, which is simpler.

**Comment by celskeggs** [comment]
Also, the suggested 24 hour grace period is far too long. 24 hours is enough time for the cluster to get stuck. I'll probably go for something like 15 minutes.
