### ISSUE TITLE
Switch from per-component build isolation to full-project build isolation

### ISSUE THREAD

**Issue by celskeggs** [sipb/homeworld#218]
Currently, individual pieces of the build will use various systems -- schroot, rkt -- to try to isolate themselves from variations in the host system.

We should have a build container (or just plain chroot) that we use for everything. It would have the normal workspace bind-mounted, and would be a consistent environment for *everything*. The only things that would be built outside of this container are the container itself and a local copy of rkt to launch it.

This would simplify and unify our build isolation tooling, and help us move towards a less complicated build system overall.

**Comment by celskeggs** [comment]
Okay, so -- what kind of isolation system do we want to use?

 - schroot?
 - containers (rkt)?
 - custom debootstrap plus chroot?

Advantages of schroot:

 - Minimal setup
 - Standard tools

Advantages of containers:

 - Network isolation
 - Possibly more reproducible build environments

Advantages of direct debootstrap and chroot:

 - No real advantages (?)

**Comment by krawthekrow** [comment]
I was looking at this, but I couldn't find  a standard way to build Debian packages without a schroot (though it's possible to start from a non-pristine schroot, which would make building faster... but then apt upgrade would need to be run manually). What do you envision for Debian packaging for the container-based option?

**Comment by celskeggs** [comment]
sbuild is optional. You can use debuild directly, which doesn't need a chroot.

**Comment by krawthekrow** [comment]
Oh, my bad, I had thought debuild needed one. I like the containers option as it offers faster compilation and better familiarity with containers.

**Comment by celskeggs** [comment]
First draft, using raw chroots, is in #275.

Next steps:

 - Confirm that everything builds under the new system.
 - Avoid having a monolithic package list; make it clear why each part of it exists. (i.e. put lists in lots of places and gather them while constructing the chroot.)
 - Handle simultaneous entries into the chroot from different terminals.
 - Try to switch to an existing chroot handling system, so that we don't need too much of our own chroot-handling code.

**Comment by celskeggs** [comment]
I believe that using systemd-nspawn is likely to be a good choice for handling chroots. (This is similar to using a container, but more light-weight.)
