### ISSUE TITLE
Prometheus runs out of memory after a few hours

### ISSUE THREAD

**Issue by krawthekrow** [sipb/homeworld#239]
When this happens, Prometheus crashes and attempting to access it results in a "service unavailable" response. Deleting the Prometheus data directory and restarting it allows Prometheus to become accessible again. We need to move to better hardware, allocate more RAM to the supervisor node or reduce the quantity of metrics collected (#222).

**Comment by celskeggs** [comment]
Hardware and memory allocation changes are unlikely to be a good long-term solution to this problem. The correct solution is to find out which metrics are causing the most trouble, and find ways to summarize them for the sake of efficiency.

**Comment by celskeggs** [comment]
Wait -- you're saying that it ran out of *memory*, not disk?

Prometheus shouldn't exceed 3GB memory usage under the default configuration.

Also, every time you restart prometheus, it takes a bit for it to return to functioning, during which time it says "service unavailable." Are you sure that you gave it a chance to finish restarting?

In any case, I'm trying to replicate this bug now.

**Comment by krawthekrow** [comment]
I think I gave it hours, but I may have misremembered. It's probably not a disk problem, since the data directory was <10GB when I cleared it. Note that I increased the VM RAM allocation to 8GB, so be sure to change it back to 4GB when replicating.

**Comment by celskeggs** [comment]
Ah, that's good to know. I've adjusted it back down to 4GB, and although the memory is filled up, there isn't a crash yet. I'll give it until tomorrow.

**Comment by celskeggs** [comment]
It's the morning, and prometheus is still working.

I cannot reproduce this bug. I'll reopen it if we see this issue again.
