### ISSUE TITLE
ssh root@egg-sandwich doesn't work for deploy.md

### ISSUE THREAD

**Issue by minced** [sipb/homeworld#268]
When running instructions from deploy.md, if one uses ``ssh root@egg-sandwich`` instead of ``ssh root@egg-sandwich.mit.edu``, the subsequent ``spire seq supervisor`` will fail. The message given ("no ECDSA host key is known for egg-sandwich.mit.edu") is likely not enough for an inexperienced developer to understand their error.

One possible remedy to specifically mention that ``ssh root@egg-sandwich`` is insufficient in the deploy instructions. Another is to make Spire accept keys for egg-sandwich as well as egg-sandwich.mit.edu.

**Comment by elefthei** [comment]
The second sounds like a better idea, since we’re already doing the same for spire infra.

**Comment by celskeggs** [comment]
The second is a difficult thing to implement, because ssh is not our component. I suggest that the best solution might be to have an explicit spire command that runs `ssh root@egg-sandwich.mit.edu`, so that we don't need to worry about people mistyping it.

**Comment by celskeggs** [comment]
It looks like this has been clarified in the relevant documentation, so I'm closing this issue.
