### ISSUE TITLE
Create vagrant file for local deployment

### ISSUE THREAD

**Issue by elefthei** [sipb/homeworld#276]
3 VMs for Master, Scheduler and one Worker should be good to start. Looks easy to start here:

http://www.thisprogrammingthing.com/2015/multiple-vagrant-vms-in-one-vagrantfile/

**Comment by celskeggs** [comment]
Is it possible to install Vagrant VMs from an ISO?

**Comment by elefthei** [comment]
Seems like it, although I don't understand why this is virtualbox specific: 
https://www.packer.io/docs/builders/virtualbox-iso.html

**Comment by celskeggs** [comment]
Since we have a local deploy mechanism now, per #315 -- which doesn't involve Vagrant -- I'm closing this.
