### ISSUE TITLE
Set up rkt with a default kvm stage1

### ISSUE THREAD

**Issue by celskeggs** [sipb/homeworld#30]
Currently, rkt just uses the default non-kvm setup.

**Comment by celskeggs** [comment]
Do I remember correctly that you were able to get this to work? At the very least, as a default for normally-launched containers?

**Comment by sdukhovni** [comment]
Yes, I believe that kvm is now the default stage1 when containers are launched with no stage1 specified.

**Comment by celskeggs** [comment]
Great. I'm closing this issue, because it seems to be ready for this weekend's cluster rebuild.
