### ISSUE TITLE
asserts used as data validation

### ISSUE THREAD

**Issue by cryslith** [sipb/homeworld#303]
There are several places where python `assert` statements appear to be used for data validation, where a test-and-raise would be more appropriate.  It is not guaranteed by the semantics of `assert` that if the condition is not met, an exception is raised.  Unless we expect that we'll want to optimize the assertions away for efficiency, I think we should just change them all to test-and-raise.

**Comment by celskeggs** [comment]
This seems like a good idea. Feel free to assign yourself if you think this should be done now; otherwise I'll put it on the backburner and take care of it later.

**Comment by celskeggs** [comment]
@cryslith do you consider this complete after #396's merger?

**Comment by cryslith** [comment]
yesOn Nov 14, 2019 10:40, Cel Skeggs <notifications@github.com> wrote:@cryslith do you consider this complete after #396's merger?
