### ISSUE TITLE
building etcd causes fatal: Not a git repository

### ISSUE THREAD

**Issue by ichung** [sipb/homeworld#313]
[homeworld] $ glass
    [...]
    launching etcd build. this may take a while...
    fatal: Not a git repository (or any parent up to mount point /tmp)
    Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not
    set).

From zephyr: cela thinks etcd tries to determine a version number based on the git repository surrounding it.

**Comment by celskeggs** [comment]
We've switched from Glass to Bazel, so this is no longer relevant.
