### ISSUE TITLE
Wrong trusted key provided to rkt

### ISSUE THREAD

**Issue by krawthekrow** [sipb/homeworld#320]
Currently, the trusted key used for rkt signature verification is copied directly from a file in homeworld-services ([here](https://github.com/sipb/homeworld/blob/fb85815c050cb0b18bd4bfaabb0d30ff0f5491df/building/components/homeworld-services/glass.yaml#L37-L39)). This ought to be the key used to sign the repositories, that is, the one indicated in branches.yaml.

**Comment by celskeggs** [comment]
Weird. I thought I'd fixed that.

**Comment by celskeggs** [comment]
Fixed by #321.
