### ISSUE TITLE
Mismatch between USB and CDROM installation in dev and prod

### ISSUE THREAD

**Issue by celskeggs** [sipb/homeworld#338]
In our development clusters, we insert our installer as an emulated CDROM. But in production, this is actually a USB drive. This means that issues like #332 and #337 don't show up in development, only in production, which is problematic.

We should make our development environments closer to the real thing by emulating a USB drive instead of a CDROM.

While we're at it, we should find a way to have disks show up as /dev/sda in test as well, rather than as /dev/vda or similar.

This would involve fixing both of our development virtualization methods:

- Update the libvirt XML configurations on toastfs-dev (under /root/hyades/)
- Update the qemu parameters generated in homeworld-admin-tools's virt.py

**Comment by krawthekrow** [comment]
Generally we cannot rely on the OS disk names (or, albeit less so, the BIOS ones), and the Debian installer doesn't appear to have any means to filter hard disks at the grub install stage, so the "correct" solution is probably to require the user to specify the disk. We can still do autodeploy by specifying the disk name in the bootline.

**Comment by celskeggs** [comment]
I was able to get booting as USB-attached hard drive to work under autodeploy, and it uncovers at least some of the same problems that #337 reported that we encountered on real hardware, which is good. (Specifically, it gets stuck at the guided partitioning page, because no one is around to proceed.)

Key command line options: `-drive media=disk,format=raw,file=cdrom.iso -drive media=disk,file=hd.img` during the initial install, and just `-drive media=disk,file=hd.img` during subsequent launches.

**Comment by celskeggs** [comment]
I've written code (in #435) to fix this mismatch. It only applies to autoinstall and not to the toastfs-dev VMs, which I consider acceptable -- we just need to have this tested in at least one place; it's okay for other parts of our testing infrastructure to use CDROM installers.

**Comment by cryslith** [comment]
Is there any reason why the fix won't also work for the toastfs VMs?

**Comment by celskeggs** [comment]
Three things:
 - the autoinstaller support depends on our ability to change the configuration between install and launch, which is harder with libvirt
 - we'd need to get libvirt to use raw disk images instead of formatted disk images
 - libvirt uses /dev/vdX instead of /dev/sdX, which we may or may not care about having consistent
