### ISSUE TITLE
Switch from ACI containers to OCI containers

### ISSUE THREAD

**Issue by celskeggs** [sipb/homeworld#353]
We current use the rkt-specific [ACI format](https://github.com/appc/spec). We should switch to the more generic [OCI format](https://www.opencontainers.org/), because then we'd have more choices for how we actually want to execute containers.

This matters, because rkt is not particularly well-supported in the community, which is giving us trouble with more recent versions of Kubernetes (see #351), and it is possible that there are better options -- all of which require us to use OCIs.

This issue is to figure out what is required for OCI migration, and then implement that work. It is likely to involve:

- [x] Updating container image creation tooling
- [x] Updating bootstrap registry serving tools
- [x] Testing rkt with the changes

**Comment by celskeggs** [comment]
Okay, so there's a key problem here: our registry model is ENTIRELY different from the Docker/OCI registry model.

We have a static page that uses ACI autodiscovery to point clients at URLs in the download location.

However, Docker/OCI images require using a more formalized Registry, which has a more complicated interface than just "a page getting served somewhere" and is generally only provided by software that provides a *mutable* registry, meaning that all of the tools are built around uploading to an existing mutable registry, or running a mutable registry, but not anything like our current immutable pointer mechanism.

This means that we have to rework how we handle uploads.

Even worse, it's not immediately obvious that there is any single ".oci" format in the same vein as the ".aci" format that can be used to move around images as a unit. Images are content-addressable, and composed of lots of nested configuration files, manifests, indexes, and blobs. This means that the only real "portable" form of an image is the uploaded form -- which, again, means having uploaded it to a mutable registry.

This is a problem, because our lifecycle model involves us not having any runtime software already deployed before setup, so there is nowhere for the build to upload these files to from bazel.

My current working solution to this is to hack up the `rules_docker` code and make it possible to generate a debian package that contains all of the image information and an upload script -- this way, the package can be installed on an administrator's machine, and the images can be uploaded from that script after the supervisor node is initially installed, allowing the supervisor node to run a standard mutable registry.

I'm not entirely convinced that this is the Correct solution, as opposed to building an immutable registry toolkit, or even running an external mutable dependency outside of the cluster, but it seems like it'll probably work?

**Comment by ichung** [comment]
Does this solution increase the overall size of the build artifact?

Also, what is wrong with just leaving our upload infrastructure as it is, and having a small script (say in spire) which pulls the images down from our static immutable registry and pushes them into the special mutable one, after supervisor setup?

**Comment by celskeggs** [comment]
It can't work in exactly the same way as before, because OCIs aren't an actual file format, and can't be passed around as individual files.

I don't believe this increases the overall size, but it does mean a bunch more stuff has to be re-uploaded when it changes.

You're right that it'd probably be better to find a way to upload them individually and pull them back down with a script, instead of routing them through apt.
