### ISSUE TITLE
Make it easier to authenticate to the cluster using the disaster recovery key

### ISSUE THREAD

**Issue by cryslith** [sipb/homeworld#371]
Especially during testing it's usually more convenient to use the disaster recovery key than other forms of authentication.  Currently the only way to do this is to remove all entries from the `root-admins` section of `setup.yaml`, which is unintuitive and unnecessarily inconvenient.  We should change spire so that it tries the disaster recovery key if other methods of authentication fail.  It should also inform the user of what authentication method it used.

**Comment by celskeggs** [comment]
Resolved by #396.
