### ISSUE TITLE
Reproducibly select version of Bazel

### ISSUE THREAD

**Issue by celskeggs** [sipb/homeworld#378]
Currently, we use the latest Bazel version in CI -- which means that sometimes master breaks because Bazel stopped supporting something one of our dependencies does.

It would be really nice to have builds that don't migrate from "working" to "broken" just because of an updated release getting published. We should find a way to install a particular version and bump it explicitly.

**Comment by krawthekrow** [comment]
Don't we already have this problem with Debian?

**Comment by celskeggs** [comment]
We should _also_ fix that one!

**Comment by celskeggs** [comment]
We should also fix that one! See #369 and #102.
