### ISSUE TITLE
Jenkins needs to time out

### ISSUE THREAD

**Issue by celskeggs** [sipb/homeworld#400]
[This build](https://hijinks.mit.edu/jenkins/job/homeworld/view/change-requests/job/PR-384/10/) kept going for over a day, holding up other jobs in the queue.

Jenkins should be configured to automatically abort builds that don't finish on time.

**Comment by celskeggs** [comment]
@krawthekrow any chance you can take care of this, since you're the most familiar with Jenkins?

**Comment by cryslith** [comment]
https://stackoverflow.com/questions/12234204/timeout-on-a-build-step-of-jenkins

**Comment by krawthekrow** [comment]
Yeah I could, I just didn't set one earlier for reasons that are no longer relevant. Would 2h total be good?

**Comment by celskeggs** [comment]
That should be fine. We can always tweak it if necessary.
