### ISSUE TITLE
Update gazelle

### ISSUE THREAD

**Issue by cryslith** [sipb/homeworld#501]
We're using an old version which lacks some nice features such as support for the new go module system.  This will be an issue when adding dependencies on go code which uses the new modules.

Since the new version supports go.mod and go.sum, I also think we should switch to autogenerating all our gazelle rules using `gazelle update-repos` once we do this.  This will make go dependency management require significantly less manual effort.

**Comment by cryslith** [comment]
Also, using the new module checksums will resolve #468 for go dependencies.

**Comment by celskeggs** [comment]
Earlier, you said:

> I also think we should switch to autogenerating all our gazelle rules using `gazelle update-repos` once we do this.

I don't think we've done that yet; do we want to either keep this issue open or split off a new one for that aspect in particular?

**Comment by cryslith** [comment]
I'll split it
