### ISSUE TITLE
Streamline ISO generation process to not require rebuilding packages

### ISSUE THREAD

**Issue by celskeggs** [sipb/homeworld#62]
We have a system by which a node installation ISO is generated from a set of locally-built packages. (//building/build-iso/generate.sh).

It should be possible to build an ISO easily -- for example, a new maintainer (or an existing maintainer with a new laptop) should easily be able to generate an ISO for installing additional nodes.

With the current system, you have to build all of the relevant helpers and packages locally, *before* you can generate the ISO. Since we're pushing all of our packages to a central debian repository (served via web.mit.edu, stored in AFS under /mit/hyades/debian/, and generated by //building/upload-debs/rebuild.sh) anyway, it should be possible to just fetch the packages from the repository, verify their signatures, and stick them into the ISO.

This will streamline the ISO generation process, which will shorten the time required to set up a new cluster or expand/repair an existing cluster.

**Comment by dmssargent** [comment]
I have a branch (https://github.com/dmssargent/homeworld/tree/automate.package.fetch.from.repo) almost ready for a PR. However, I still need to verify the downloaded package from its listed hash.

From https://github.com/dmssargent/homeworld/commit/35816d224f79ad49bc5d65d2959def7b5d5928a3#commitcomment-24336835, what should I use to actually add those files into the ISO?

**Comment by celskeggs** [comment]
What does the status of this look like?

Also, changes to this script were made for DC4; you should consider rebasing your work against the HEAD of `feature-ki-deployable` before you submit a PR.

**Comment by dmssargent** [comment]
Will do.

My goal for opening a PR is by the end of this weekend, ideally by Saturday.

**Comment by celskeggs** [comment]
Since #89 has been merged, I'm marking this as closed! 🎊
