### ISSUE TITLE
Add support for kerberos gateway to keycommon library

### ISSUE THREAD

**Issue by celskeggs** [sipb/homeworld#70]
The keycommon library current includes an interface by which software (like the keyclient) can connect to the keyserver with certificate authentication or bootstrap token authentication.

Kerberos authentication (via knc and the kerberos gateway) needs to be supported by the library as well, if possible, to simplify the implementation of administrative scripts.

This is likely necessary for #52.

**Comment by sdukhovni** [comment]
I believe this is fixed by my commits on feature-ki / feature-ki-deployable.

**Comment by celskeggs** [comment]
Fixed on head of feature-ki-deployable; deployed and tested as part of DC4.
