### ISSUE TITLE
Upgrade golang to more recent v1.8.6 version

### ISSUE THREAD

**Issue by celskeggs** [sipb/homeworld#99]
Upstream: ~[v1.8.4](https://golang.org/dl/)~ ~[v1.8.5](https://golang.org/dl/)~ [v1.8.6](https://golang.org/dl/)

Upstream update checklist:
- [x] Ensure upstream version is latest.
- [x] Review changelogs for breaking changes.
- [x] Securely verify upstream release hash.
- [x] Add upgrade-golang-1.8.6 branch with update.
- [x] Implement any repackaging changes.
- [ ] Test cluster deployment with changes.
- [ ] Merge changes.

**Comment by celskeggs** [comment]
1.8.4 is not the most recent version, but is the most recent version that we're willing to use with Kubernetes.

**Comment by celskeggs** [comment]
I'm deferring this to DC6, because neither of the security fixes are critical for homeworld.

**Comment by celskeggs** [comment]
Golang is now at 1.8.5, not 1.8.4, so we should update directly to 1.8.5.

**Comment by quentinmit** [comment]
Golang is up to 1.9.2 FYI.

**Comment by celskeggs** [comment]
Yeah, the major version bump you're talking about is issue #100, but migrating from 1.8 -> 1.9 is a large change, and 1.8.3 -> 1.8.5 is a small change.

(We previously had trouble bumping major versions on Kubernetes, because of backwards compatibility issues in Go. So we'll have to keep a version of Go 1.8 in our repo until Kubernetes updates to 1.9.)

**Comment by krawthekrow** [comment]
Since #150 is in DC6 (#100 is ostensibly in DC7, but #150 depends on #100), I assume this issue is obsolete?

**Comment by celskeggs** [comment]
It's not yet clear whether upgrading to 1.9 will break anything, so we don't yet know whether we actually need this.
